# Generated by Django 6.0.3 on 2026-07-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=50)),
                ('density_percentage', models.DecimalField(decimal_places=2, max_digits=5, max_length=5)),
                ('estimated_count', models.IntegerField(default=0)),
                ('queue_wait_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(default='normal', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
