# Generated by Django 6.0.3 on 2026-07-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcoMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('carbon_saved_tonnes', models.FloatField(default=0)),
                ('renewable_energy_pct', models.FloatField(default=0)),
                ('water_recycled_pct', models.FloatField(default=0)),
                ('waste_recycled_pct', models.FloatField(default=0)),
                ('ev_count', models.IntegerField(default=0)),
                ('solar_kwh', models.FloatField(default=0)),
                ('plastic_bottles_avoided', models.IntegerField(default=0)),
                ('trees_planted', models.IntegerField(default=0)),
                ('eco_score', models.FloatField(default=0, help_text='Overall eco grade 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eco Metric Snapshot',
                'ordering': ['-date'],
            },
        ),
    ]
