# Generated by Django 6.0.3 on 2026-07-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=50)),
                ('capacity_total', models.IntegerField()),
                ('capacity_occupied', models.IntegerField()),
                ('capacity_reserved', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
