# Generated by Django 6.0.3 on 2026-07-14 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('flag', models.CharField(blank=True, max_length=10)),
                ('group', models.CharField(blank=True, max_length=5)),
                ('fifa_ranking', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=80)),
                ('capacity', models.IntegerField()),
                ('surface', models.CharField(default='Grass', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('kickoff_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('match_minute', models.IntegerField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('stage', models.CharField(default='Group Stage', max_length=50)),
                ('group', models.CharField(blank=True, max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='away_matches', to='stadium.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='home_matches', to='stadium.team')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='matches', to='stadium.venue')),
            ],
        ),
    ]
